[profile.default]
src = 'src'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'forge-cache'
solc_version = '0.8.25'
optimizer = true
optimizer_runs = 200
via_ir = false
# debug revert strings looks experimental and fails the CI because of an unexpected error.
revert_strings = "default"
names = true
sizes = true
gas_reports = ["BVault", "CrossLending", "CrossLiquidation", "IsolateLending", "IsolateLiquidation", "FlashLoan", "YieldEthStakingLido", "YieldRegistry", "YieldEthStakingLido", "YieldEthStakingEtherfi", "YieldSavingsDai"]
fs_permissions = [{ access = "read", path = "./"}]
ffi = true

[rpc_endpoints]
mainnet = "https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}"
sepolia = "https://eth-sepolia.g.alchemy.com/v2/${ALCHEMY_KEY}"
tenderly = "https://rpc.tenderly.co/fork/${TENDERLY_FORK_ID}"

[profile.default.fuzz]
runs = 1024

[profile.production.fuzz]
runs = 256

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
